# Generated by scripts/homebrew-formula.sh; do not edit by hand.
class Nyxr < Formula
  desc "Network scanner with service identification and packet capture"
  homepage "https://github.com/matusso/nyxr"
  version "0.13.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/matusso/nyxr/releases/download/v0.13.1/nyxr-v0.13.1-darwin-arm64.tar.gz"
      sha256 "f0ce85197abcd3052c714246ab916e513ed9def80775cf6f5e771b136e8fbfcc"
    end
    on_intel do
      url "https://github.com/matusso/nyxr/releases/download/v0.13.1/nyxr-v0.13.1-darwin-amd64.tar.gz"
      sha256 "a6815f0442b3140f832e31f6b93a2935cdd4b69e3100eae4f0c80c6fd2e128ce"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/matusso/nyxr/releases/download/v0.13.1/nyxr-v0.13.1-linux-arm64.tar.gz"
      sha256 "22c7442d516942adef8c4c5b224c93cee1c388264c3afb9a4cfc01134e9c4fa9"
    end
    on_intel do
      url "https://github.com/matusso/nyxr/releases/download/v0.13.1/nyxr-v0.13.1-linux-amd64.tar.gz"
      sha256 "3aca41a0d319aa19006dc14b4941acabc0248621df37cef5f5c21cb1af30d2c1"
    end
  end

  def install
    bin.install "nyxr", "nyxr-packetd"
    generate_completions_from_executable(bin/"nyxr", "completion")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/nyxr version")
  end
end
