# Generated by scripts/homebrew-formula.sh; do not edit by hand.
class Nyxr < Formula
  desc "Network scanner with service identification and packet capture"
  homepage "https://github.com/matusso/nyxr"
  version "0.11.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/matusso/nyxr/releases/download/v0.11.1/nyxr-v0.11.1-darwin-arm64.tar.gz"
      sha256 "7f6ee145d154492e6c31c12351ffd813df1a3c64d266101b77669342134c527f"
    end
    on_intel do
      url "https://github.com/matusso/nyxr/releases/download/v0.11.1/nyxr-v0.11.1-darwin-amd64.tar.gz"
      sha256 "0037f54a27ea4b25dfc583f6705c3191f9e40a4bbbadcc5fb87a6230e25a2a44"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/matusso/nyxr/releases/download/v0.11.1/nyxr-v0.11.1-linux-arm64.tar.gz"
      sha256 "27ca12f6499be9052a3c8e4931d3fa269be43348ec0f3861ebdd35157b762198"
    end
    on_intel do
      url "https://github.com/matusso/nyxr/releases/download/v0.11.1/nyxr-v0.11.1-linux-amd64.tar.gz"
      sha256 "47932c00d8187f88c59b576eb78335d73c4987e5629cc697a887efce6657496e"
    end
  end

  def install
    bin.install "nyxr", "nyxr-packetd"
    generate_completions_from_executable(bin/"nyxr", "completion")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/nyxr version")
  end
end
