# Generated by scripts/homebrew-formula.sh; do not edit by hand.
class Nyxr < Formula
  desc "Network scanner with service identification and packet capture"
  homepage "https://github.com/matusso/nyxr"
  version "0.6.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/matusso/nyxr/releases/download/v0.6.0/nyxr-v0.6.0-darwin-arm64.tar.gz"
      sha256 "36f5bcc7fabad147e22e62dc265922be2ccfbcfbe579ee051a2b60438ab1e260"
    end
    on_intel do
      url "https://github.com/matusso/nyxr/releases/download/v0.6.0/nyxr-v0.6.0-darwin-amd64.tar.gz"
      sha256 "6791496b121d9fb311d8780632ac29e183d2ab4ee76cc68974079bcc0c6bff7c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/matusso/nyxr/releases/download/v0.6.0/nyxr-v0.6.0-linux-arm64.tar.gz"
      sha256 "7917f5efa4f1ca148554dfd1c9332afecb7fd0d4b7bdec7aaff9f8df9b2f3562"
    end
    on_intel do
      url "https://github.com/matusso/nyxr/releases/download/v0.6.0/nyxr-v0.6.0-linux-amd64.tar.gz"
      sha256 "f614fec09c5b3fd5d2c66bcb5851d0e947b791c4ae98753940aa6b35a6ae17a5"
    end
  end

  def install
    bin.install "nyxr", "nyxr-packetd"
    generate_completions_from_executable(bin/"nyxr", "completion")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/nyxr version")
  end
end
