#!/usr/bin/env bash
# Render the Homebrew formula for a release from its SHA256SUMS file.
# Usage: scripts/homebrew-formula.sh v0.6.0 dist/SHA256SUMS > Formula/nyxr.rb
set -euo pipefail

tag=${1:?usage: $0 <tag> <SHA256SUMS>}
sums=${2:?usage: $0 <tag> <SHA256SUMS>}
version=${tag#v}
base="https://github.com/matusso/nyxr/releases/download/$tag"

sha() {
  local file="nyxr-$tag-$1.tar.gz" sum
  sum=$(awk -v f="$file" '$2 == f || $2 == "*" f { print $1 }' "$sums")
  [[ -n "$sum" ]] || { echo "missing checksum for $file" >&2; exit 1; }
  echo "$sum"
}

cat <<RUBY
# Generated by scripts/homebrew-formula.sh; do not edit by hand.
class Nyxr < Formula
  desc "Network scanner with service identification and packet capture"
  homepage "https://github.com/matusso/nyxr"
  version "$version"
  license "MIT"

  on_macos do
    on_arm do
      url "$base/nyxr-$tag-darwin-arm64.tar.gz"
      sha256 "$(sha darwin-arm64)"
    end
    on_intel do
      url "$base/nyxr-$tag-darwin-amd64.tar.gz"
      sha256 "$(sha darwin-amd64)"
    end
  end

  on_linux do
    on_arm do
      url "$base/nyxr-$tag-linux-arm64.tar.gz"
      sha256 "$(sha linux-arm64)"
    end
    on_intel do
      url "$base/nyxr-$tag-linux-amd64.tar.gz"
      sha256 "$(sha linux-amd64)"
    end
  end

  def install
    bin.install "nyxr", "nyxr-packetd"
    generate_completions_from_executable(bin/"nyxr", "completion")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/nyxr version")
  end
end
RUBY
